# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
#    -   id: check-added-large-files
    # -   id: check-merge-conflict
    # -   id: detect-private-key
-   repo: https://github.com/fsfe/reuse-tool
    rev: v0.11.1
    hooks:
    - id: reuse
-   repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.3.5
    hooks:
        - id: go-fmt
        # - id: go-vet
        #   args: [./kaybee]
        - id: go-lint
        - id: go-imports
        # - id: go-cyclo
          args: [-over=15]
        - id: validate-toml
        - id: no-go-testing
        # - id: gometalinter
        # - id: golangci-lint
        # - id: go-critic
        # - id: go-unit-tests
        # - id: go-build
